### ISSUE TITLE
Link on r-bloggers.com is wrong

### ISSUE THREAD

**Issue by b-long** [andrie/cran-network-structure#1]
Your link on [r-bloggers](http://www.r-bloggers.com/differences-in-the-network-structure-of-cran-and-bioconductor/) is directing people to `https://github.com/andrie/cran-network-structure%20` , while it should be directing people to `https://github.com/andrie/cran-network-structure`.

**Comment by andrie** [comment]
Thank you for spotting this.  I have fixed the original blog at http://blog.revolutionanalytics.com/2015/08/differences-in-the-network-structure-of-cran-and-bioconductor.html

Hopefully this propagates directly to R-bloggers.

Pinging @talgalili for help. (Tal, does R-bloggers automatically update if the original blog entry is changed?)

**Comment by b-long** [comment]
Happy to help :+1:

**Comment by talgalili** [comment]
I fixed it manually (the site doesn't refresh older posts).

Cheers,
Tal

**Comment by andrie** [comment]
Thanks, @talgalili !
