### ISSUE TITLE
bad restore file error

### ISSUE THREAD

**Issue by abitofalchemy** [andrie/cran-network-structure#3]
I tried out the steps in your [blog post](http://blog.revolutionanalytics.com/2015/07/creating-network-graphs-using-javascript-directly-from-r.html), but I get the following error message.: 

```
> load("/Path/Downloads/pdb-CRAN.rds")
Error: bad restore file magic number (file may be corrupted) -- no data loaded
In addition: Warning message:
file ‘pdb-CRAN.rds’ has magic number 'X'
  Use of save versions prior to 2 is deprecated 
> 
```

**Comment by andrie** [comment]
You're trying a step I didn't use in the blog post.

It seems that you are trying to read an `.rds` file using `load()`.  I didn't use `load()` but `readRDS()`.
